608 plugin weekdays
Tracardi/tracardi pull request #641
Opened 2022-08-11 19:31 UTC by Mefpef

Type pull request title with short description (#608 )

add plugin which check whether is weekend day or not and register it in setup_plugins.py

**Please** following this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Give the same name to the pull request as the name of ticket 
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Test your code throughly before PR.
 
If your pull request is about ~20 lines of code add license information in your code in form of comment. i.e. # License: MIT, Author:  Your name.

To make clear that you license your contribution under the MIT you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [MIT license](https://opensource.org/licenses/MIT)

PRs without ticked MIT license will bot be accepted - Sorry.

2022-08-12 08:19 UTC, atompie requested changes
Plugin seems ok but manual is missing.

2022-08-12 08:19 UTC, atompie commented on tracardi/process_engine/action/v1/weekdays_checker_action.py
> +
Manual is missing.

2022-08-12 08:30 UTC, Mefpef commented on tracardi/process_engine/action/v1/weekdays_checker_action.py
> +
I will add the manual this afternoon

2022-08-15 22:55 UTC, atompie approved these changes

2022-08-15 22:55 UTC, merged