646 field contains string
Tracardi/tracardi pull request #664
Opened 2022-08-23 15:59 UTC by Mefpef

Type pull request title with short description (#646 )

646 field contains string

add contains string plugin and register it
----

**Please** following this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Give the same name to the pull request as the name of ticket 
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Test your code throughly before PR.
 
If your pull request is about ~20 lines of code add license information in your code in form of comment. i.e. # License: MIT, Author:  Your name.

To make clear that you license your contribution under the MIT you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [MIT license](https://opensource.org/licenses/MIT)

PRs without ticked MIT license will bot be accepted - Sorry.

2022-08-23 18:27 UTC, DawidekZagajnik requested changes
refactoring and formatting needed

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +class Config(PluginConfig):
I'd move it to another directory, should be somewhere in operations or strings section of /action/v1, with config separated in .mode.config file

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +    def if_prefix_is_empty(cls, value):
def validate_prefix(cls, value):

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +        if self.config.prefix in dot[self.config.field]:
error prone, you should first check if dot[self.config.field] is iterable, and log, then throw an exception with an explanation

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +                "field": "",
should default to None

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +    field: str
should be validated

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +    field: str
if not empty as well

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +                                name="Type string or reference to string which you want to check.",
type string or path to the string that you want to check.

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +                                        "label": "Payload field",
label: path

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +                                id="prefix",
rename it to substring

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +                                id="prefix",
basically everywhere

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +            name='Contain string',
Contains

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +            group=["Flow control"],
more like strings or operations

2022-08-23 18:27 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/contains_string_action.py
> +                outputs={"true": PortDoc(desc="This port returns payload if field contains defined string."),
formatting

2022-08-25 15:44 UTC, atompie approved these changes

2022-08-25 16:40 UTC, merged