658 contains pattern action
Tracardi/tracardi pull request #697
Opened 2022-09-17 15:26 UTC by Mefpef

Type pull request title with short description (#658 )

Contains pattern action plugin #658 

done:
plugin
tests
register plugin

----

**Please** following this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Give the same name to the pull request as the name of ticket 
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Test your code throughly before PR.
 
If your pull request is about ~20 lines of code add license information in your code in form of comment. i.e. # License: MIT, Author:  Your name.

To make clear that you license your contribution under the MIT you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [MIT license](https://opensource.org/licenses/MIT)

PRs without ticked MIT license will not be accepted - Sorry.

2022-09-18 10:19 UTC, DawidekZagajnik requested changes

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +        if value == "":
"if not value" is gonna cover more cases

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +    def validate_prefix(cls, value):
validate_field

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +        if value == "":
same as above

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +        if not isinstance(value, str) or isinstance(value, list):
if not (isintance(value, str) or isintance(value, list)). For now, List will raise an error that is unwanted.

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +                    founded_patterns.append(k)
found, founded stands for "ufundowany"

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +        if self.config.pattern == "url":
use elif, slight performance increase

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +        return Result(port="false", value="Didn't find any patterns")
do not return string as value. That is going to raise an error in the further execution. Return something like value={"found": None} or {"message": "Did not find any pattern"}.

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +                             PortDoc(desc="This port returns payload if field doesnt contain defined pattern.")}
doesn't contain

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +                outputs={"true": PortDoc(desc="This port returns payload if field contains defined pattern."),
these outputs does not return payload. They return new objects.

2022-09-18 10:19 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +        founded_patterns = []
should be declared below "if" statement in the next line.

2022-09-18 10:23 UTC, DawidekZagajnik commented on tracardi/process_engine/action/v1/operations/contains_pattern/plugin.py
> +        if value == "":
one more thing: make this field an Enum, so it checks if it is one of email, ip, date, etc. even if the plugin is configured using advanced config.

2022-09-19 08:30 UTC, atompie requested changes
Could you please make the changes suggested by David. Thanks.

2022-09-19 20:23 UTC, merged