Sitemap plugin
Tracardi/tracardi pull request #877
Opened 2024-10-18 00:39 UTC by mattcam

Type pull request title with short description (#876)

This request will add a plugin that fetches a list URLs from a sitemap.

This code has been tested against 1.0.x

I hereby declare this contribution to be licensed under the [MIT license](https://opensource.org/licenses/MIT).

2024-10-18 10:01 UTC, atompie requested changes

2024-10-18 10:01 UTC, atompie commented on tracardi/process_engine/action/v1/sitemap_action.py
> +        async with aiohttp.ClientSession(headers=headers) as session:
We have already build class for the http calls, that is integrated with plugins. 

```python
from tracardi.service.tracardi_http_client import HttpClient

        async with HttpClient(3, [200], headers=headers) as client:
            async with client.get(url=url) as response:
                result = await response.text()
```

It has integrated retries and accepted headers: `3, [200]`

Could you use this.

2024-10-18 10:01 UTC, atompie commented on tracardi/process_engine/action/v1/sitemap_action.py
> +            manual="Sitemap",
This should be lowercase: `sitemap`.

I already prepared docs for your plugin. Could you please review it:

# Sitemap

Fetches a list of URLs from a sitemap.

# Version

1.0.3

## Description

The Sitemap plugin is designed to extract URLs from a given sitemap or a sitemap index. It takes a sitemap path as input and returns a list of URLs contained within that sitemap. This plugin can process nested sitemaps and follows the sitemap structure to provide a comprehensive list of URLs.

The plugin works as follows:

1. **Sitemap Path Input**: The plugin accepts a sitemap path provided via dot notation. This path should point to a URL where the sitemap can be accessed.
2. **Fetching Sitemap Content**: Using this URL, the plugin fetches the content of the sitemap. It supports both main sitemaps and sitemap indexes.
3. **Processing Sitemap**: The plugin processes the sitemap index to retrieve any nested sitemap URLs. For each nested sitemap, the URLs are extracted and combined into a single list.
4. **Returning the Result**: The plugin then returns all the URLs as a list.

If any error occurs during these steps, an error message will be returned.

# Inputs and Outputs

- **Input Port**: payload
  - Accepts a payload object. The input should contain the path to the sitemap in dot notation format. The sitemap path should be valid and accessible.

- **Output Ports**:
  - **Result** (result): Returns a dictionary containing the list of URLs fetched from the sitemap.
    - Example Output:
      ```json
      {
        "urls": [
          "https://example.com/page1",
          "https://example.com/page2"
        ]
      }
      ```
  - **Error** (`error`): Returns an error message if the plugin fails to fetch or process the sitemap.
    - Example Output:
      ```json
      {
        "message": "Error fetching sitemap: 404"
      }
      ```

# Configuration

- **Sitemap Path** (`sitemap_path`):
  - The URL where the sitemap can be found. The path must be specified using dot notation.
  - This value must not be empty.

# JSON Configuration

```json
{
  "sitemap_path": "event@sitemap.url"
}
```

# Required resources

This plugin does not require external resources to be configured.

# Event prerequisites

This plugin works for all events and does not require synchronous execution.

# Errors

- **"Sitemap path must not be empty."**
  - This error occurs if the `sitemap_path` configuration is left blank.
- **"Error fetching sitemap: [status code]"**
  - This error occurs when the plugin fails to fetch the sitemap from the provided URL, usually due to an invalid or inaccessible URL.
- **"Error processing sitemap index: [error details]"**
  - This error occurs when the sitemap index cannot be processed due to issues with the XML structure.
- **"Error processing sitemap: [error details]"**
  - This error occurs if there is a problem parsing the XML content of the sitemap, often due to invalid or malformed XML.


It should be placed in `tracardi/documentation repo under docs/docs/getting_started/processes/workflow/actions` as file `sitemap.md`.

2024-10-19 23:20 UTC, mattcam commented
For requested changes refer: 

1. Package change: https://github.com/Tracardi/tracardi/pull/877/commits/d3e3b4adfe264dd74db6aa43ee6014c55beaf7eb
2. Documentation: https://github.com/Tracardi/documentation/pull/1

2024-10-21 05:05 UTC, merged